const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
    TOGGLE_FILTER: 'TOGGLE_FILTER',
    FETCH_PRODUCT_DETAILS_START: 'FETCH_PRODUCT_DETAILS_START',
    FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_FAILURE: 'FETCH_PRODUCT_DETAILS_FAILURE'
};

export default ShopActionTypes;