const ShopActionTypes = {
    FETCH_PRODUCTS_LIST_START: 'FETCH_PRODUCTS_LIST_START',
    FETCH_PRODUCTS_LIST_SUCCESS: 'FETCH_PRODUCTS_LIST_SUCCESS',
    FETCH_PRODUCTS_LIST_FAILURE: 'FETCH_PRODUCTS_LIST_FAILURE',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
    TOGGLE_FILTER: 'TOGGLE_FILTER'
};

export default ShopActionTypes;